// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for TaskStatus.
const (
	Done       TaskStatus = "done"
	InProgress TaskStatus = "in_progress"
	Todo       TaskStatus = "todo"
)

// Defines values for TeamMemberRole.
const (
	Admin  TeamMemberRole = "admin"
	Member TeamMemberRole = "member"
	Owner  TeamMemberRole = "owner"
)

// AcceptInviteRequest defines model for AcceptInviteRequest.
type AcceptInviteRequest struct {
	Code string `json:"code"`
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	Token string `json:"token"`
	User  User   `json:"user"`
}

// Comment defines model for Comment.
type Comment struct {
	Body      string    `json:"body"`
	CreatedAt time.Time `json:"created_at"`
	Id        UUID      `json:"id"`
	TaskId    UUID      `json:"task_id"`
	UserId    UUID      `json:"user_id"`
}

// CommentsListResponse defines model for CommentsListResponse.
type CommentsListResponse struct {
	Items   []Comment `json:"items"`
	Page    int       `json:"page"`
	PerPage int       `json:"per_page"`
	Total   int       `json:"total"`
}

// CreateCommentRequest defines model for CreateCommentRequest.
type CreateCommentRequest struct {
	Body string `json:"body"`
}

// CreateTaskRequest defines model for CreateTaskRequest.
type CreateTaskRequest struct {
	AssigneeId  *UUID       `json:"assignee_id,omitempty"`
	Description *string     `json:"description,omitempty"`
	Status      *TaskStatus `json:"status,omitempty"`
	TeamId      UUID        `json:"team_id"`
	Title       string      `json:"title"`
}

// CreateTeamRequest defines model for CreateTeamRequest.
type CreateTeamRequest struct {
	Name string `json:"name"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error   string  `json:"error"`
	Message *string `json:"message,omitempty"`
}

// InvalidAssignee defines model for InvalidAssignee.
type InvalidAssignee struct {
	AssigneeId UUID `json:"assignee_id"`
	TaskId     UUID `json:"task_id"`
	TeamId     UUID `json:"team_id"`
}

// Invite defines model for Invite.
type Invite struct {
	Code      string              `json:"code"`
	CreatedAt time.Time           `json:"created_at"`
	Email     openapi_types.Email `json:"email"`
	Id        UUID                `json:"id"`
	InviterId UUID                `json:"inviter_id"`
	TeamId    UUID                `json:"team_id"`
}

// InviteRequest defines model for InviteRequest.
type InviteRequest struct {
	Email openapi_types.Email `json:"email"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// Task defines model for Task.
type Task struct {
	AssigneeId  *UUID      `json:"assignee_id,omitempty"`
	CompletedAt *time.Time `json:"completed_at,omitempty"`
	CreatedAt   time.Time  `json:"created_at"`
	CreatedBy   UUID       `json:"created_by"`
	Description *string    `json:"description,omitempty"`
	Id          UUID       `json:"id"`
	Status      TaskStatus `json:"status"`
	TeamId      UUID       `json:"team_id"`
	Title       string     `json:"title"`
	UpdatedAt   *time.Time `json:"updated_at,omitempty"`
}

// TaskHistory defines model for TaskHistory.
type TaskHistory struct {
	ChangedAt time.Time              `json:"changed_at"`
	ChangedBy UUID                   `json:"changed_by"`
	Changes   map[string]interface{} `json:"changes"`
	Id        UUID                   `json:"id"`
	TaskId    UUID                   `json:"task_id"`
}

// TaskHistoryListResponse defines model for TaskHistoryListResponse.
type TaskHistoryListResponse struct {
	Items []TaskHistory `json:"items"`
}

// TaskStatus defines model for TaskStatus.
type TaskStatus string

// TasksListResponse defines model for TasksListResponse.
type TasksListResponse struct {
	Items   []Task `json:"items"`
	Page    int    `json:"page"`
	PerPage int    `json:"per_page"`
	Total   int    `json:"total"`
}

// Team defines model for Team.
type Team struct {
	CreatedAt time.Time `json:"created_at"`
	CreatedBy UUID      `json:"created_by"`
	Id        UUID      `json:"id"`
	Name      string    `json:"name"`
}

// TeamMember defines model for TeamMember.
type TeamMember struct {
	CreatedAt time.Time      `json:"created_at"`
	Role      TeamMemberRole `json:"role"`
	TeamId    UUID           `json:"team_id"`
	UserId    UUID           `json:"user_id"`
}

// TeamMemberRole defines model for TeamMember.Role.
type TeamMemberRole string

// TeamSummary defines model for TeamSummary.
type TeamSummary struct {
	DoneLast7d   int    `json:"done_last_7d"`
	MembersCount int    `json:"members_count"`
	TeamId       UUID   `json:"team_id"`
	TeamName     string `json:"team_name"`
}

// TeamTopCreators defines model for TeamTopCreators.
type TeamTopCreators struct {
	Creators []UserTaskCount `json:"creators"`
	TeamId   UUID            `json:"team_id"`
	TeamName string          `json:"team_name"`
}

// TeamsListResponse defines model for TeamsListResponse.
type TeamsListResponse struct {
	Items []Team `json:"items"`
}

// UUID defines model for UUID.
type UUID = openapi_types.UUID

// UpdateCommentRequest defines model for UpdateCommentRequest.
type UpdateCommentRequest struct {
	Body string `json:"body"`
}

// UpdateTaskRequest defines model for UpdateTaskRequest.
type UpdateTaskRequest struct {
	AssigneeId  *UUID       `json:"assignee_id,omitempty"`
	Description *string     `json:"description,omitempty"`
	Status      *TaskStatus `json:"status,omitempty"`
	Title       *string     `json:"title,omitempty"`
}

// User defines model for User.
type User struct {
	CreatedAt time.Time           `json:"created_at"`
	Email     openapi_types.Email `json:"email"`
	Id        UUID                `json:"id"`
}

// UserTaskCount defines model for UserTaskCount.
type UserTaskCount struct {
	TasksCreated int  `json:"tasks_created"`
	UserId       UUID `json:"user_id"`
}

// CommentId defines model for CommentId.
type CommentId = UUID

// Page defines model for Page.
type Page = int

// PerPage defines model for PerPage.
type PerPage = int

// TaskId defines model for TaskId.
type TaskId = UUID

// TeamId defines model for TeamId.
type TeamId = UUID

// BadRequest defines model for BadRequest.
type BadRequest = ErrorResponse

// Forbidden defines model for Forbidden.
type Forbidden = ErrorResponse

// NotFound defines model for NotFound.
type NotFound = ErrorResponse

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorResponse

// GetApiV1ReportsTopCreatorsParams defines parameters for GetApiV1ReportsTopCreators.
type GetApiV1ReportsTopCreatorsParams struct {
	// Month Месяц в формате YYYY-MM
	Month *string `form:"month,omitempty" json:"month,omitempty"`
}

// GetApiV1TasksParams defines parameters for GetApiV1Tasks.
type GetApiV1TasksParams struct {
	TeamId     UUID        `form:"team_id" json:"team_id"`
	Status     *TaskStatus `form:"status,omitempty" json:"status,omitempty"`
	AssigneeId *UUID       `form:"assignee_id,omitempty" json:"assignee_id,omitempty"`
	Page       *Page       `form:"page,omitempty" json:"page,omitempty"`
	PerPage    *PerPage    `form:"per_page,omitempty" json:"per_page,omitempty"`
}

// GetApiV1TasksIdCommentsParams defines parameters for GetApiV1TasksIdComments.
type GetApiV1TasksIdCommentsParams struct {
	Page    *Page    `form:"page,omitempty" json:"page,omitempty"`
	PerPage *PerPage `form:"per_page,omitempty" json:"per_page,omitempty"`
}

// PostApiV1LoginJSONRequestBody defines body for PostApiV1Login for application/json ContentType.
type PostApiV1LoginJSONRequestBody = LoginRequest

// PostApiV1RegisterJSONRequestBody defines body for PostApiV1Register for application/json ContentType.
type PostApiV1RegisterJSONRequestBody = RegisterRequest

// PostApiV1TasksJSONRequestBody defines body for PostApiV1Tasks for application/json ContentType.
type PostApiV1TasksJSONRequestBody = CreateTaskRequest

// PutApiV1TasksIdJSONRequestBody defines body for PutApiV1TasksId for application/json ContentType.
type PutApiV1TasksIdJSONRequestBody = UpdateTaskRequest

// PostApiV1TasksIdCommentsJSONRequestBody defines body for PostApiV1TasksIdComments for application/json ContentType.
type PostApiV1TasksIdCommentsJSONRequestBody = CreateCommentRequest

// PutApiV1TasksIdCommentsCommentIdJSONRequestBody defines body for PutApiV1TasksIdCommentsCommentId for application/json ContentType.
type PutApiV1TasksIdCommentsCommentIdJSONRequestBody = UpdateCommentRequest

// PostApiV1TeamsJSONRequestBody defines body for PostApiV1Teams for application/json ContentType.
type PostApiV1TeamsJSONRequestBody = CreateTeamRequest

// PostApiV1TeamsInvitesAcceptJSONRequestBody defines body for PostApiV1TeamsInvitesAccept for application/json ContentType.
type PostApiV1TeamsInvitesAcceptJSONRequestBody = AcceptInviteRequest

// PostApiV1TeamsIdInviteJSONRequestBody defines body for PostApiV1TeamsIdInvite for application/json ContentType.
type PostApiV1TeamsIdInviteJSONRequestBody = InviteRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Вход и получение JWT
	// (POST /api/v1/login)
	PostApiV1Login(c *gin.Context)
	// Регистрация пользователя
	// (POST /api/v1/register)
	PostApiV1Register(c *gin.Context)
	// Задачи, где assignee не состоит в команде
	// (GET /api/v1/reports/invalid-assignees)
	GetApiV1ReportsInvalidAssignees(c *gin.Context)
	// Отчет по командам (кол-во участников, done за 7 дней)
	// (GET /api/v1/reports/team-summary)
	GetApiV1ReportsTeamSummary(c *gin.Context)
	// Топ-3 пользователей по созданным задачам за месяц
	// (GET /api/v1/reports/top-creators)
	GetApiV1ReportsTopCreators(c *gin.Context, params GetApiV1ReportsTopCreatorsParams)
	// Список задач с фильтрами и пагинацией
	// (GET /api/v1/tasks)
	GetApiV1Tasks(c *gin.Context, params GetApiV1TasksParams)
	// Создать задачу (только член команды)
	// (POST /api/v1/tasks)
	PostApiV1Tasks(c *gin.Context)
	// Обновить задачу (проверка прав)
	// (PUT /api/v1/tasks/{id})
	PutApiV1TasksId(c *gin.Context, id TaskId)
	// Список комментариев задачи
	// (GET /api/v1/tasks/{id}/comments)
	GetApiV1TasksIdComments(c *gin.Context, id TaskId, params GetApiV1TasksIdCommentsParams)
	// Добавить комментарий к задаче
	// (POST /api/v1/tasks/{id}/comments)
	PostApiV1TasksIdComments(c *gin.Context, id TaskId)
	// Удалить комментарий
	// (DELETE /api/v1/tasks/{id}/comments/{comment_id})
	DeleteApiV1TasksIdCommentsCommentId(c *gin.Context, id TaskId, commentId CommentId)
	// Обновить комментарий
	// (PUT /api/v1/tasks/{id}/comments/{comment_id})
	PutApiV1TasksIdCommentsCommentId(c *gin.Context, id TaskId, commentId CommentId)
	// История изменений задачи
	// (GET /api/v1/tasks/{id}/history)
	GetApiV1TasksIdHistory(c *gin.Context, id TaskId)
	// Список команд, где состоит пользователь
	// (GET /api/v1/teams)
	GetApiV1Teams(c *gin.Context)
	// Создать команду (пользователь становится owner)
	// (POST /api/v1/teams)
	PostApiV1Teams(c *gin.Context)
	// Принять приглашение по коду
	// (POST /api/v1/teams/invites/accept)
	PostApiV1TeamsInvitesAccept(c *gin.Context)
	// Пригласить пользователя в команду (owner/admin)
	// (POST /api/v1/teams/{id}/invite)
	PostApiV1TeamsIdInvite(c *gin.Context, id TeamId)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// PostApiV1Login operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1Login(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostApiV1Login(c)
}

// PostApiV1Register operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1Register(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostApiV1Register(c)
}

// GetApiV1ReportsInvalidAssignees operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1ReportsInvalidAssignees(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiV1ReportsInvalidAssignees(c)
}

// GetApiV1ReportsTeamSummary operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1ReportsTeamSummary(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiV1ReportsTeamSummary(c)
}

// GetApiV1ReportsTopCreators operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1ReportsTopCreators(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiV1ReportsTopCreatorsParams

	// ------------- Optional query parameter "month" -------------

	err = runtime.BindQueryParameter("form", true, false, "month", c.Request.URL.Query(), &params.Month)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter month: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiV1ReportsTopCreators(c, params)
}

// GetApiV1Tasks operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1Tasks(c *gin.Context) {

	var err error

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiV1TasksParams

	// ------------- Required query parameter "team_id" -------------

	if paramValue := c.Query("team_id"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument team_id is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "team_id", c.Request.URL.Query(), &params.TeamId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter team_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", c.Request.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter status: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "assignee_id" -------------

	err = runtime.BindQueryParameter("form", true, false, "assignee_id", c.Request.URL.Query(), &params.AssigneeId)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter assignee_id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "per_page" -------------

	err = runtime.BindQueryParameter("form", true, false, "per_page", c.Request.URL.Query(), &params.PerPage)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter per_page: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiV1Tasks(c, params)
}

// PostApiV1Tasks operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1Tasks(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostApiV1Tasks(c)
}

// PutApiV1TasksId operation middleware
func (siw *ServerInterfaceWrapper) PutApiV1TasksId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id TaskId

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutApiV1TasksId(c, id)
}

// GetApiV1TasksIdComments operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1TasksIdComments(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id TaskId

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params GetApiV1TasksIdCommentsParams

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameter("form", true, false, "page", c.Request.URL.Query(), &params.Page)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter page: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Optional query parameter "per_page" -------------

	err = runtime.BindQueryParameter("form", true, false, "per_page", c.Request.URL.Query(), &params.PerPage)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter per_page: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiV1TasksIdComments(c, id, params)
}

// PostApiV1TasksIdComments operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1TasksIdComments(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id TaskId

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostApiV1TasksIdComments(c, id)
}

// DeleteApiV1TasksIdCommentsCommentId operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiV1TasksIdCommentsCommentId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id TaskId

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "comment_id" -------------
	var commentId CommentId

	err = runtime.BindStyledParameterWithOptions("simple", "comment_id", c.Param("comment_id"), &commentId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter comment_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteApiV1TasksIdCommentsCommentId(c, id, commentId)
}

// PutApiV1TasksIdCommentsCommentId operation middleware
func (siw *ServerInterfaceWrapper) PutApiV1TasksIdCommentsCommentId(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id TaskId

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	// ------------- Path parameter "comment_id" -------------
	var commentId CommentId

	err = runtime.BindStyledParameterWithOptions("simple", "comment_id", c.Param("comment_id"), &commentId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter comment_id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PutApiV1TasksIdCommentsCommentId(c, id, commentId)
}

// GetApiV1TasksIdHistory operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1TasksIdHistory(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id TaskId

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiV1TasksIdHistory(c, id)
}

// GetApiV1Teams operation middleware
func (siw *ServerInterfaceWrapper) GetApiV1Teams(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetApiV1Teams(c)
}

// PostApiV1Teams operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1Teams(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostApiV1Teams(c)
}

// PostApiV1TeamsInvitesAccept operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1TeamsInvitesAccept(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostApiV1TeamsInvitesAccept(c)
}

// PostApiV1TeamsIdInvite operation middleware
func (siw *ServerInterfaceWrapper) PostApiV1TeamsIdInvite(c *gin.Context) {

	var err error

	// ------------- Path parameter "id" -------------
	var id TeamId

	err = runtime.BindStyledParameterWithOptions("simple", "id", c.Param("id"), &id, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter id: %w", err), http.StatusBadRequest)
		return
	}

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostApiV1TeamsIdInvite(c, id)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/api/v1/login", wrapper.PostApiV1Login)
	router.POST(options.BaseURL+"/api/v1/register", wrapper.PostApiV1Register)
	router.GET(options.BaseURL+"/api/v1/reports/invalid-assignees", wrapper.GetApiV1ReportsInvalidAssignees)
	router.GET(options.BaseURL+"/api/v1/reports/team-summary", wrapper.GetApiV1ReportsTeamSummary)
	router.GET(options.BaseURL+"/api/v1/reports/top-creators", wrapper.GetApiV1ReportsTopCreators)
	router.GET(options.BaseURL+"/api/v1/tasks", wrapper.GetApiV1Tasks)
	router.POST(options.BaseURL+"/api/v1/tasks", wrapper.PostApiV1Tasks)
	router.PUT(options.BaseURL+"/api/v1/tasks/:id", wrapper.PutApiV1TasksId)
	router.GET(options.BaseURL+"/api/v1/tasks/:id/comments", wrapper.GetApiV1TasksIdComments)
	router.POST(options.BaseURL+"/api/v1/tasks/:id/comments", wrapper.PostApiV1TasksIdComments)
	router.DELETE(options.BaseURL+"/api/v1/tasks/:id/comments/:comment_id", wrapper.DeleteApiV1TasksIdCommentsCommentId)
	router.PUT(options.BaseURL+"/api/v1/tasks/:id/comments/:comment_id", wrapper.PutApiV1TasksIdCommentsCommentId)
	router.GET(options.BaseURL+"/api/v1/tasks/:id/history", wrapper.GetApiV1TasksIdHistory)
	router.GET(options.BaseURL+"/api/v1/teams", wrapper.GetApiV1Teams)
	router.POST(options.BaseURL+"/api/v1/teams", wrapper.PostApiV1Teams)
	router.POST(options.BaseURL+"/api/v1/teams/invites/accept", wrapper.PostApiV1TeamsInvitesAccept)
	router.POST(options.BaseURL+"/api/v1/teams/:id/invite", wrapper.PostApiV1TeamsIdInvite)
}
